name: CI
on:
  - push

jobs:
  job1:
    outputs:
      url: ${{ steps.step1.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: step1
        run: echo "::set-output name=url::bassam"
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Step 2
        run: echo ${{needs.job1.outputs.url}}
